language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
before_script:
  - psql -c 'create database grit;' -U postgres
  - mix ecto.migrate
after_script:
  - mix coveralls.travis
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  - DATABASE_URL=postgres://postgres@localhost/grit MIX_ENV=test
